type: http
name: List loan applications
url: '{{baseUrl}}/applications?status=denied&productType=home_equity&limit=25&offset=0'
method: GET
headers:
  - key: Accept
    value: application/json
queryParams:
  - key: status
    value: denied
    description: Filter by application status
  - key: productType
    value: home_equity
    description: Filter by loan product type
  - key: limit
    value: '25'
  - key: offset
    value: '0'
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "data": [
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 2255.7075979276965,
                "termMonths": 8312,
                "status": "approved",
                "createdAt": "2022-11-16T20:25:58.021Z",
                "updatedAt": "2020-11-15T15:02:53.819Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "in_progress",
                  "decision": "approved",
                  "riskScore": 33,
                  "evaluatedAt": "1992-06-01T12:24:09.855Z"
                }
              },
              {
                "id": "string",
                "applicantId": "string",
                "productType": "string",
                "requestedAmount": 5704.762701454769,
                "termMonths": 9125,
                "status": "approved",
                "createdAt": "1978-07-11T07:54:12.737Z",
                "updatedAt": "1986-05-06T05:54:08.791Z",
                "underwritingResult": {
                  "applicationId": "string",
                  "status": "pending",
                  "decision": "denied",
                  "riskScore": 55,
                  "evaluatedAt": "2014-09-06T20:19:15.050Z"
                }
              }
            ],
            "total": 5249,
            "limit": 6907,
            "offset": 8687
          }
      headers:
        - key: Content-Type
          value: application/json
    name: List of applications
