type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 1375.325011789401,
            "termMonths": 1119,
            "status": "withdrawn",
            "createdAt": "2022-06-11T02:39:57.724Z",
            "updatedAt": "1989-06-13T21:07:44.534Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "in_progress",
              "decision": "denied",
              "riskScore": 5,
              "evaluatedAt": "1983-02-10T15:33:26.062Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
