type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 6216.6116393801385,
            "termMonths": 3408,
            "status": "denied",
            "createdAt": "1982-11-17T07:41:30.638Z",
            "updatedAt": "1994-01-25T13:22:44.057Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "in_progress",
              "decision": "approved",
              "riskScore": 98,
              "evaluatedAt": "1952-04-26T01:20:54.633Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
