type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 2231.268999982419,
            "termMonths": 6804,
            "status": "withdrawn",
            "createdAt": "1977-06-21T17:22:31.419Z",
            "updatedAt": "1968-03-07T22:42:05.190Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "completed",
              "decision": "approved",
              "riskScore": 95,
              "evaluatedAt": "2007-10-18T14:58:39.920Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
